# Generated by Django 3.1.2 on 2020-10-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
