# Generated by Django 3.1.2 on 2020-12-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201029_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.TextField(blank=True, choices=[('listening', 'listening'), ('reading', 'reading')], max_length=20, null=True),
        ),
    ]
