# Generated by Django 3.1.1 on 2020-10-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200930_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
