# Generated by Django 3.1.1 on 2020-10-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_student_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='instructor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
