# Generated by Django 3.1.2 on 2021-10-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210118_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='service',
            new_name='my_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rank',
        ),
    ]
